# Generated by Django 5.2.5 on 2025-08-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=500)),
                ("published_date", models.DateTimeField()),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("page_count", models.IntegerField()),
                ("langush", models.CharField(default="English", max_length=50)),
            ],
        ),
    ]
